baseURL = "https://rf-collection-dev.netlify.app/"
languageCode = "en-us"
title = "Unhealthy Obsession"
theme = "rucking-fotten"
enableRobotsTXT = true

[taxonomies]
  style = "styles"
  size = "sizes"

[params]
  description = "The ongoing Rucking Fotten collection of Jacob Proffer, started in 2019."
  images = ["/images/social.jpg"]
